import React from 'react';
import Link from "next/link";
import Head from "next/head";

const MainContainer = ({children, title}) => {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>

            <div className="navigation">

            </div>
            <div>
                {children}
            </div>
        </>
    );
};

export default MainContainer;
